/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var message_echo_pb = require('../../message/echo_pb.js');
goog.object.extend(proto, message_echo_pb);
var message_meta_pb = require('../../message/meta_pb.js');
goog.object.extend(proto, message_meta_pb);
goog.exportSymbol('proto.grpc_demo_go.protobuf.service.test_a.EchoRequest', null, global);
goog.exportSymbol('proto.grpc_demo_go.protobuf.service.test_a.EchoResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc_demo_go.protobuf.service.test_a.EchoRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.grpc_demo_go.protobuf.service.test_a.EchoRequest.displayName = 'proto.grpc_demo_go.protobuf.service.test_a.EchoRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grpc_demo_go.protobuf.service.test_a.EchoResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.displayName = 'proto.grpc_demo_go.protobuf.service.test_a.EchoResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc_demo_go.protobuf.service.test_a.EchoRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc_demo_go.protobuf.service.test_a.EchoRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc_demo_go.protobuf.service.test_a.EchoRequest}
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc_demo_go.protobuf.service.test_a.EchoRequest;
  return proto.grpc_demo_go.protobuf.service.test_a.EchoRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc_demo_go.protobuf.service.test_a.EchoRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc_demo_go.protobuf.service.test_a.EchoRequest}
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc_demo_go.protobuf.service.test_a.EchoRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc_demo_go.protobuf.service.test_a.EchoRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoRequest.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.grpc_demo_go.protobuf.service.test_a.EchoRequest.prototype.setMessage = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grpc_demo_go.protobuf.service.test_a.EchoResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    meta: (f = msg.getMeta()) && message_meta_pb.Meta.toObject(includeInstance, f),
    data: (f = msg.getData()) && message_echo_pb.Echo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grpc_demo_go.protobuf.service.test_a.EchoResponse}
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grpc_demo_go.protobuf.service.test_a.EchoResponse;
  return proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grpc_demo_go.protobuf.service.test_a.EchoResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grpc_demo_go.protobuf.service.test_a.EchoResponse}
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new message_meta_pb.Meta;
      reader.readMessage(value,message_meta_pb.Meta.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    case 2:
      var value = new message_echo_pb.Echo;
      reader.readMessage(value,message_echo_pb.Echo.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grpc_demo_go.protobuf.service.test_a.EchoResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      message_meta_pb.Meta.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      message_echo_pb.Echo.serializeBinaryToWriter
    );
  }
};


/**
 * optional grpc_demo_go.protobuf.message.Meta meta = 1;
 * @return {?proto.grpc_demo_go.protobuf.message.Meta}
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.prototype.getMeta = function() {
  return /** @type{?proto.grpc_demo_go.protobuf.message.Meta} */ (
    jspb.Message.getWrapperField(this, message_meta_pb.Meta, 1));
};


/** @param {?proto.grpc_demo_go.protobuf.message.Meta|undefined} value */
proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.prototype.setMeta = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.prototype.clearMeta = function() {
  this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional grpc_demo_go.protobuf.message.Echo data = 2;
 * @return {?proto.grpc_demo_go.protobuf.message.Echo}
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.prototype.getData = function() {
  return /** @type{?proto.grpc_demo_go.protobuf.message.Echo} */ (
    jspb.Message.getWrapperField(this, message_echo_pb.Echo, 2));
};


/** @param {?proto.grpc_demo_go.protobuf.message.Echo|undefined} value */
proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.prototype.setData = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.prototype.clearData = function() {
  this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grpc_demo_go.protobuf.service.test_a.EchoResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.grpc_demo_go.protobuf.service.test_a);
